### ISSUE TITLE
How to use search / replace / regex functions?

### ISSUE THREAD

**Issue by vatterspun** [phitsc/txtproc#2]
Could you provide a little detail on the syntax around search/replace/regex?  I couldn't seem to make those work, but I'm particularly interested in listing out all the results of a regex code on a text document e.g. hexidecimal values with the code [\x41-\x45]{4}

**Comment by phitsc** [comment]
txtproc is written in the D programming language and uses D's regex library. According to the D regex library documentation it uses the ECMAScript syntax with some extensions.

Calling txtproc as follows:

`.\txtproc\txtproc.exe -v -e SearchRegex -p '[\x41-\x45]{4}'`

with the following clipboard contents:

```
0x1234
0xABCD
0xAB23
0xCDEE
0xFFFF
0xAAAA
```

gives me the following output:

![SearchRegex x41-x45](https://user-images.githubusercontent.com/29787/83979478-f697c800-a90e-11ea-96f4-26da28a02d53.png)

Is this what you are after?

**Comment by vatterspun** [comment]
Yes, great stuff -- thanks :)
